"""Tests for Markdown report generation."""

from mkforge import (
    BlockQuote,
    BulletList,
    Chapter,
    CodeBlock,
    HorizontalRule,
    Image,
    LineBreak,
    NumberedList,
    Paragraph,
    Report,
    Section,
    Table,
    Text,
)
from mkforge.markdown import render_report


def test_report_renders_core_markdown_blocks() -> None:
    """Requirement: render the supported Markdown leaf node set."""
    report = Report(title="Status").add(
        Chapter("Summary").add(
            Paragraph("All checks passed."),
            Paragraph(
                (
                    Text("Use "),
                    Text("mkforge", style="code"),
                    LineBreak(),
                    Text("boldly", style="bold"),
                    Text(" and "),
                    Text("carefully", style="italic"),
                    Text(" while "),
                    Text("removing", style="strikethrough"),
                    Text(" ambiguity."),
                ),
            ),
            CodeBlock("print('ok')", language="python"),
            Table(("Check", "Status"), (("lint", "pass"), ("test", "pass"))),
            BulletList(("fast", "typed")),
            NumberedList(("compose", "render")),
            Image("assets/chart.png", alt="Chart", title="Quality"),
            HorizontalRule(),
            BlockQuote("Generated by automation.\nReviewed by humans."),
            Text("Plain ending."),
        ),
    )
    expected = (
        "# Status\n\n"
        "## Summary\n\n"
        "All checks passed.\n\n"
        "Use `mkforge`  \n"
        "**boldly** and *carefully* while ~~removing~~ ambiguity.\n\n"
        "```python\nprint('ok')\n```\n\n"
        "| Check | Status |\n"
        "| --- | --- |\n"
        "| lint | pass |\n"
        "| test | pass |\n\n"
        "- fast\n- typed\n\n"
        "1. compose\n2. render\n\n"
        '![Chart](assets/chart.png "Quality")\n\n'
        "---\n\n"
        "> Generated by automation.\n> Reviewed by humans.\n\n"
        "Plain ending."
    )
    actual = report.render()
    if actual != expected:
        raise AssertionError(actual)


def test_report_renders_metadata_toc_and_numbering() -> None:
    """Requirement: render frontmatter, TOC, and automatic numbering."""
    report = Report(
        title="Audit",
        metadata={
            "title": "Audit",
            "author": "Antoine Barre",
            "date": "2026-05-30",
            "version": "1.0.0",
            "description": "Quality report",
            "tags": ["quality", "markdown"],
            "draft": False,
            "reviewed": None,
        },
        toc=True,
        auto_numbering=True,
    ).add(
        Chapter("Overview").add(
            Section("Scope").add(
                Section("Inclusions").add(Paragraph("Runtime package.")),
            ),
        ),
    )
    expected = (
        "---\n"
        "title: Audit\n"
        "author: Antoine Barre\n"
        "date: 2026-05-30\n"
        "version: 1.0.0\n"
        "description: Quality report\n"
        "tags:\n"
        "  - quality\n"
        "  - markdown\n"
        "draft: false\n"
        "reviewed: null\n"
        "---\n\n"
        "# Audit\n\n"
        "- [Overview](#overview)\n"
        "  - [Scope](#scope)\n"
        "    - [Inclusions](#inclusions)\n\n"
        "## 1. Overview\n\n"
        "### 1.1. Scope\n\n"
        "#### 1.1.1. Inclusions\n\n"
        "Runtime package."
    )
    actual = render_report(report)
    if actual != expected:
        raise AssertionError(actual)
